HIDDEN TREASURES DASHBOARD
Administrative Alert System
========================================

{{ $severity_indicator ?? '!' }} {{ $severity_display ?? 'ALERT' }}: {{ $title ?? 'System Alert' }}

{{ $description ?? 'An important event requires your attention.' }}

{{ str_repeat('=', 70) }}

@yield('content')

{{ str_repeat('-', 70) }}

RECOMMENDED ACTIONS
-------------------
@if($severity === 'CRITICAL')
IMMEDIATE ACTION REQUIRED:
• Review the alert immediately
• Verify all system security measures
• Check for unauthorized access or data breaches
• Consider restricting access if suspicious
• Contact system administrator if needed

@elseif($severity === 'HIGH')
PRIORITY ATTENTION REQUIRED:
• Investigate the event within the next hour
• Review system logs for related events
• Validate the legitimacy of the action
• Monitor for similar occurrences

@else
MONITOR AND REVIEW:
• Review during regular system checks
• Monitor for similar patterns
• Update policies if needed
@endif

@if($action_url)
View Details: {{ $action_url }}
@endif

{{ str_repeat('=', 70) }}

TECHNICAL INFORMATION
---------------------
Event ID: {{ $event->occurredAt->format('Y-m-d_H-i-s') }}_{{ $category ?? 'unknown' }}
Timestamp: {{ $occurred_at->format('Y-m-d H:i:s T') }}
Event Type: {{ class_basename($event) }}
Severity: {{ $severity_display ?? 'Unknown' }}

@if(isset($context['ip_address']))
IP Address: {{ $context['ip_address'] }}
@endif

@if(isset($context['user_agent']))
User Agent: {{ $context['user_agent'] }}
@endif

@if(isset($context['location']))
Location: {{ $context['location'] }}
@endif

{{ str_repeat('=', 70) }}

SYSTEM INFORMATION
------------------
Dashboard: {{ config('app.url') }}
Support: {{ config('app.url') }}/support
Notification Settings: {{ config('app.url') }}/settings/notifications

This alert was automatically generated by the Hidden Treasures Dashboard
administrative system. If you believe this was sent in error, please contact
your system administrator immediately.

Confidentiality Notice: This message contains confidential information
intended only for the specified recipients. Unauthorized disclosure is
prohibited.

© {{ date('Y') }} Hidden Treasures Dashboard. All rights reserved.