@extends('emails.administrative-alerts.text.base')

@section('content')
{{ $severity_indicator ?? '!' }} {{ $severity_display ?? 'ALERT' }} DETAILS
====================================================

Event Type: {{ class_basename($event) }}
Category: {{ $category ?? 'Unknown' }}
Severity: {{ $severity_display ?? 'Unknown' }}
Occurred: {{ $occurred_at->format('M j, Y g:i A T') }}

@if($initiated_by)
Initiated By: {{ $initiated_by->name }} ({{ $initiated_by->email }})
Role: {{ $initiated_by->role ?? 'Unknown' }}
@endif

EVENT DESCRIPTION
-----------------
{{ $description ?? 'An event has occurred that requires your attention.' }}

@if(isset($context))
ADDITIONAL INFORMATION
----------------------
@foreach($context as $key => $value)
@if(is_scalar($value))
{{ ucfirst(str_replace('_', ' ', $key)) }}: {{ $value }}
@endif
@endforeach
@endif


@if($severity === 'CRITICAL')
🚨 CRITICAL ALERT - IMMEDIATE ACTION REQUIRED 🚨
===============================================
This is a critical alert that requires your immediate attention:

1. Review this alert immediately
2. Assess the impact and scope of the issue
3. Take appropriate corrective actions
4. Notify relevant stakeholders if necessary
5. Document all actions taken
6. Monitor for follow-up issues

Failure to address this critical alert may result in:
• System downtime or data loss
• Security vulnerabilities
• Business disruption
• Financial impact
• Compliance violations

@elseif($severity === 'HIGH')
⚠️ HIGH PRIORITY ALERT - ATTENTION REQUIRED ⚠️
=============================================
This is a high-priority alert that requires your prompt attention:

1. Review this alert within the next hour
2. Investigate the underlying cause
3. Implement appropriate solutions
4. Monitor for related issues
5. Update relevant documentation

This alert may impact:
• System performance
• User experience
• Business operations
• Data integrity

@else)
ℹ️ NOTIFICATION - REVIEW ADVISED ℹ️
==================================
This is an informational alert for your awareness:

1. Review this alert during regular checks
2. Monitor for related events
3. Update processes if needed
4. Add to trend analysis

This alert is for:
• Informational purposes
• Trend monitoring
• Process improvement
• Documentation updates
@endif


@if($action_url)
VIEW DETAILS
------------
To view more information and take action, visit:
{{ $action_url }}
@endif


@if(isset($context['recommended_actions']))
RECOMMENDED ACTIONS
-------------------
@foreach($context['recommended_actions'] as $index => $action)
{{ $index + 1 }}. {{ $action }}
@endforeach
@endif


@if(isset($context['impact_assessment']))
IMPACT ASSESSMENT
------------------
{{ $context['impact_assessment'] }}
@endif


@if(isset($context['next_steps']))
NEXT STEPS
----------
@foreach($context['next_steps'] as $step)
• {{ $step }}
@endforeach
@endif


@if(isset($context['technical_details']))
TECHNICAL INFORMATION
---------------------
{{ $context['technical_details'] }}
@endif


@if(isset($context['contact_information']))
CONTACT INFORMATION
-------------------
@foreach($context['contact_information'] as $role => $contact))
{{ $role }}: {{ $contact }}
@endforeach
@endif


MONITORING & FOLLOW-UP
----------------------
1. Monitor for related events or patterns
2. Document this event in appropriate logs
3. Review during next system/operations review
4. Update alerting thresholds if needed
5. Share lessons learned with relevant team members

This alert was automatically generated by the Hidden Treasures Dashboard
administrative system based on predefined rules and thresholds.
@endsection